// <auto-generated />
//
// To parse this JSON data, add NuGet 'Newtonsoft.Json' then do:
//
//    using QuickType;
//
//    var responseObj = ResponseObj.FromJson(jsonString);

namespace APIVerve.API.DANERecordValidator
{
    using System;
    using System.Collections.Generic;

    using System.Globalization;
    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;

    public partial class ResponseObj
    {
        [JsonProperty("status")]
        public string Status { get; set; }

        [JsonProperty("error")]
        public object Error { get; set; }

        [JsonProperty("data")]
        public Data Data { get; set; }
    }

    public partial class Data
    {
        [JsonProperty("raw_record")]
        public string RawRecord { get; set; }

        [JsonProperty("parsed")]
        public Parsed Parsed { get; set; }

        [JsonProperty("interpretation")]
        public Interpretation Interpretation { get; set; }

        [JsonProperty("validation")]
        public Validation Validation { get; set; }
    }

    public partial class Interpretation
    {
        [JsonProperty("usage")]
        public Matching Usage { get; set; }

        [JsonProperty("selector")]
        public Matching Selector { get; set; }

        [JsonProperty("matching")]
        public Matching Matching { get; set; }

        [JsonProperty("security_level")]
        public string SecurityLevel { get; set; }

        [JsonProperty("recommendation")]
        public string Recommendation { get; set; }
    }

    public partial class Matching
    {
        [JsonProperty("name")]
        public string Name { get; set; }

        [JsonProperty("description")]
        public string Description { get; set; }

        [JsonProperty("full_description")]
        public string FullDescription { get; set; }
    }

    public partial class Parsed
    {
        [JsonProperty("name")]
        public string Name { get; set; }

        [JsonProperty("port")]
        public long Port { get; set; }

        [JsonProperty("protocol")]
        public string Protocol { get; set; }

        [JsonProperty("hostname")]
        public string Hostname { get; set; }

        [JsonProperty("ttl")]
        public long Ttl { get; set; }

        [JsonProperty("class")]
        public string Class { get; set; }

        [JsonProperty("usage")]
        public long Usage { get; set; }

        [JsonProperty("selector")]
        public long Selector { get; set; }

        [JsonProperty("matching")]
        public long Matching { get; set; }

        [JsonProperty("certificate_data")]
        public string CertificateData { get; set; }

        [JsonProperty("certificate_data_length")]
        public long CertificateDataLength { get; set; }
    }

    public partial class Validation
    {
        [JsonProperty("is_valid")]
        public bool IsValid { get; set; }

        [JsonProperty("certificate_data_format")]
        public string CertificateDataFormat { get; set; }

        [JsonProperty("certificate_data_length_valid")]
        public bool CertificateDataLengthValid { get; set; }
    }
}
